### PR TITLE
Add list view for shortened URLs, convert README to Markdown

### PR DESCRIPTION
**Pull request by jeffbyrnes**
This is a rehash of #3, primarily meant as an example of what those commits can look like when rebased, and broken up a bit into more discreet chunks of work.

This _does_ include a whole swatch of whitespace changes, but it’s what I’ve encountered to be best practice, so I hope they’re not too disruptive to the actual changes being brought in here.

h/t to @bueltge for the original work; all I did was clean things up.

### CODE REVIEW

**Comment by splorp** [comment]
Now all we need if for @shauninman to kindly merge the pull request. Haven‘t seen him around these part for quite some time, so we may need to work off a fork instead.

**Comment by bueltge** [comment]
@jeffbyrnes thanks for your helping hands! I see inside the #3 and read your links, that I use this much more often.

@splorp I hope it. A fork is possible, but currently is the central base and download on the site from @shauninman and I think, this should stay.

**Comment by splorp** [comment]
@bueltge I agree with keeping the changes with the main code branch. However, it may be a while before we hear from Mr Inman. He and his wife are expecting their first baby this week and imagine that he’ll have his hands full.

**Comment by bueltge** [comment]
> expecting their first baby

This is a wonderful point to wait for a merge. The source is not helpful on this topic, his new fork - the baby - is important and not a final class ;) 
I have two childs and get every day new improvements and challenges, much more and much unknown as on source code.

**Review by bueltge — APPROVED** [review]

**Comment by jeffbyrnes** [comment]
@bueltge thanks for the "official" approval over a year later :)

No idea if we'll ever see this merge to master; maybe @shauninman would be willing to grant collaborator rights to us.

That said, if you prefer this version of the work, I'd say you should close #3, to simplify things.

You & I can use my fork (I'm happy to grant you collaborator rights) for now.

**Comment by jeffbyrnes** [comment]
Closing in favor of #5

**Pull request closed without merging**
